"""The streaming writer reproduces real `p13-corpus-6` journals exactly.

This is the byte proof that matters. The synthetic journals in `test_journal_stream.py` prove the
mechanics; these are the actual accepted corpus files — 35 to 423 MB of real Polymarket book
updates, real BTC ticks and the real decisions they produced — decoded and written back out.

They are opened read-only and never touched. The corpus is not modified, moved or regenerated by
anything here; a temporary copy is written elsewhere, hashed, compared and deleted.

Skipped unless `P13_CORPUS_DIR` names a directory that has them, because decoding a 423 MB
journal takes half a minute and several gigabytes, and the regression suite runs on every commit.
The evidence run is recorded in `docs/evidence/`.
"""

from __future__ import annotations

import hashlib
import os
from pathlib import Path

import pytest

from maker5m.replay import decode_journal, encode_journal, write_journal_stream

CORPUS = Path(os.environ.get("P13_CORPUS_DIR", "")) if os.environ.get("P13_CORPUS_DIR") else None

# One small, one near the corpus median, one of the largest. Named rather than globbed, so a
# missing file is a failure to explain and not a silently shorter test.
REAL_JOURNALS = (
    "btc-updown-5m-1787890800.journal.ndjson",
    "btc-updown-5m-1787907000.journal.ndjson",
    "btc-updown-5m-1787925900.journal.ndjson",
)

pytestmark = pytest.mark.skipif(
    CORPUS is None or not CORPUS.is_dir(),
    reason="set P13_CORPUS_DIR to the p13-corpus-6 markets directory to run the real byte proof",
)


def _sha256_and_size(path: Path) -> tuple[str, int]:
    digest = hashlib.sha256()
    size = 0
    with path.open("rb") as handle:
        while chunk := handle.read(1 << 22):
            digest.update(chunk)
            size += len(chunk)
    return digest.hexdigest(), size


@pytest.mark.parametrize("name", REAL_JOURNALS)
def test_streaming_a_real_journal_reproduces_it_byte_for_byte(name: str, tmp_path: Path) -> None:
    assert CORPUS is not None
    original = CORPUS / name
    if not original.is_file():
        pytest.skip(f"{name} is not in {CORPUS}")
    before_sha, before_size = _sha256_and_size(original)

    journal = decode_journal(original.read_bytes())
    written = write_journal_stream(tmp_path / name, journal)

    after_sha, after_size = _sha256_and_size(tmp_path / name)
    assert written.sha256 == before_sha, "the writer's running digest disagrees with the original"
    assert written.bytes_written == before_size
    assert after_sha == before_sha, "the file on disk is not the journal that was recorded"
    assert after_size == before_size
    # And the original is exactly as it was found.
    assert _sha256_and_size(original) == (before_sha, before_size)


@pytest.mark.parametrize("name", REAL_JOURNALS[:1])
def test_a_real_journal_still_encodes_the_old_way_to_the_same_bytes(name: str) -> None:
    """`encode_journal` was refactored onto the stream. It must not have changed its output."""
    assert CORPUS is not None
    original = CORPUS / name
    if not original.is_file():
        pytest.skip(f"{name} is not in {CORPUS}")
    raw = original.read_bytes()
    assert encode_journal(decode_journal(raw)) == raw
